In [1]:
import pandas as pd
import numpy as np

from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

import joblib

In [2]:
df = pd.read_csv("../data/creditcard.csv")

In [4]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [5]:
df.shape

(284807, 31)

In [6]:
X = df.drop("Class", axis=1)
y = df["Class"]

print(X.shape)
print(y.shape)

(284807, 30)
(284807,)

In [7]:
X_train = X[y == 0]

print(X_train.shape)

(284315, 30)

In [8]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

In [9]:
X_train_scaled.shape

(284315, 30)

In [10]:
model = IsolationForest(
    n_estimators=100,
    contamination=0.005,
    random_state=42,
    n_jobs=-1
)

In [11]:
model

IsolationForest(contamination=0.005, n_jobs=-1, random_state=42)

In [12]:
model.fit(X_train_scaled)

IsolationForest(contamination=0.005, n_jobs=-1, random_state=42)

In [13]:
X_scaled = scaler.transform(X)

X_scaled.shape

(284807, 30)

In [14]:
predictions = model.predict(X_scaled)

In [15]:
np.unique(predictions, return_counts=True)

(array([-1,  1]), array([  1630, 283177]))

In [16]:
y_pred = np.where(predictions == -1, 1, 0)

np.unique(y_pred, return_counts=True)

(array([0, 1]), array([283177,   1630]))

In [17]:
cm = confusion_matrix(y, y_pred)

cm

array([[282893,   1422],
       [   284,    208]])

In [18]:
precision = precision_score(y, y_pred)
recall = recall_score(y, y_pred)
f1 = f1_score(y, y_pred)

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Precision: 0.1276073619631902
Recall: 0.42276422764227645
F1 Score: 0.19604147031102734

In [19]:
from sklearn.metrics import classification_report

print(classification_report(y, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00    284315
           1       0.13      0.42      0.20       492

    accuracy                           0.99    284807
   macro avg       0.56      0.71      0.60    284807
weighted avg       1.00      0.99      1.00    284807

In [20]:
anomaly_scores = model.decision_function(X_scaled)

In [21]:
anomaly_scores[:10]

array([0.20022496, 0.23890253, 0.13902316, 0.19110199, 0.21223366,
       0.23370786, 0.2279901 , 0.11703957, 0.19214211, 0.23425821])

In [22]:
risk_scores = ((anomaly_scores.max() - anomaly_scores) / (anomaly_scores.max() - anomaly_scores.min())) * 100

In [23]:
risk_scores[:10]

array([15.3758189 ,  6.06393296, 30.11056607, 17.57223693, 12.48464326,
        7.31458444,  8.69117424, 35.40326259, 17.32181962,  7.18208508])

In [24]:
pd.Series(risk_scores).describe()

count    284807.000000
mean         14.883978
std          10.824447
min           0.000000
25%           7.322413
50%          12.517791
75%          19.165992
max         100.000000
dtype: float64

In [25]:
results_df = df.copy()

results_df["Risk_Score"] = risk_scores

results_df.sort_values(by="Risk_Score", ascending=False).head(10)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V22,V23,V24,V25,V26,V27,V28,Amount,Class,Risk_Score
274771,166198.0,-35.548539,-31.850484,-48.325589,15.304184,-113.743307,73.301626,120.589494,-27.347360,-3.872425,...,5.712303,-1.581098,4.584549,4.554683,3.415636,31.612198,-15.430084,25691.16,0,100.000000
173353,121450.0,-28.262775,-26.551515,-15.930586,6.945207,-19.203497,13.461737,23.718783,-9.419314,5.264773,...,-2.932575,-22.459170,1.771003,-3.684737,-0.106886,4.071877,-2.383081,4861.64,0,97.040712
173054,121340.0,-22.132223,-19.815536,-11.183644,4.829787,-13.128465,10.689779,18.257057,-8.685409,5.250410,...,-1.969170,-18.416215,1.376122,-2.965101,0.149369,4.077221,-1.975801,4543.64,0,96.067817
195218,130956.0,-23.209602,-20.056784,-11.851649,4.811523,-16.658993,13.348714,23.475217,-8.385575,4.094708,...,1.039620,2.990196,0.230236,3.214827,1.047926,-0.037677,14.046301,4248.34,0,95.069993
220090,142019.0,-37.558067,-29.335992,-24.962322,8.413616,-35.182120,21.550496,36.877368,-8.915982,5.046566,...,-1.150828,-7.800902,1.272716,1.965365,0.767817,3.248189,13.013546,5964.95,0,95.043257
39769,39954.0,-56.407510,-72.715728,-6.605265,16.491217,34.801666,-26.160506,-19.399981,-1.501300,6.967698,...,-1.272167,7.893082,0.767805,5.376595,0.163672,-8.358317,33.847808,1201.83,0,94.823967
231454,146772.0,-35.905105,-31.041362,-19.472908,9.216960,-18.863553,10.713326,16.687265,-9.609234,3.296559,...,-3.016337,-19.331255,0.987774,-2.180899,-0.172480,6.228140,-2.830091,3552.96,0,94.789998
176335,122723.0,-35.274010,-34.889342,-15.070015,9.211564,-6.226835,3.828063,10.778805,-6.462003,6.588395,...,-4.722186,-26.429741,1.765486,-4.564506,-0.594620,1.110848,-0.714247,1676.60,0,94.599032
219640,141812.0,-34.614374,-29.145460,-14.985962,7.677798,-8.846632,5.571214,13.167616,-4.717060,6.091319,...,-1.323059,-3.329551,0.452444,2.410307,0.580394,-1.363536,15.632689,1417.29,0,94.351368
58465,48401.0,-36.802320,-63.344698,-20.645794,16.715537,-20.672064,7.694002,24.956587,-4.730111,-2.687312,...,-10.933144,-17.173665,1.180700,-7.025783,-2.534330,-3.602479,3.450224,19656.53,0,93.875346

In [26]:
top_100 = results_df.sort_values(
    by="Risk_Score",
    ascending=False
).head(100)

top_100["Class"].value_counts()

Class
0    85
1    15
Name: count, dtype: int64

In [27]:
import joblib

In [33]:
import os

os.getcwd()

'C:\\Users\\amdra\\OneDrive\\Desktop\\CreditCard Fraud\\notebooks'

In [34]:
os.listdir("..")

['data', 'notebooks', 'venv']

In [35]:
import os

os.makedirs("../model", exist_ok=True)

In [36]:
os.listdir("..")

['data', 'model', 'notebooks', 'venv']

In [37]:
joblib.dump(model, "../model/fraud_model.pkl")
joblib.dump(scaler, "../model/scaler.pkl")

['../model/scaler.pkl']

In [38]:
os.listdir("../model")

['fraud_model.pkl', 'scaler.pkl']

In [39]:
os.listdir("../model")

['fraud_model.pkl', 'scaler.pkl']

In [40]:
results_df = df.copy()

results_df["Predicted_Class"] = y_pred

results_df["Risk_Score"] = risk_scores

results_df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V23,V24,V25,V26,V27,V28,Amount,Class,Predicted_Class,Risk_Score
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0,0,15.375819
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0,0,6.063933
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0,0,30.110566
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0,0,17.572237
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0,0,12.484643

In [41]:
results_df.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class', 'Predicted_Class', 'Risk_Score'],
      dtype='str')